ensure_dir <- function(path) {
  if (!dir.exists(path)) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }

  normalizePath(path, winslash = "/", mustWork = FALSE)
}

format_fixed <- function(x, digits = 3) {
  stopifnot(length(x) == 1, is.numeric(x), is.finite(x))
  formatC(round(x, digits), format = "f", digits = digits)
}

latex_escape <- function(x) {
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x
}

write_generated_values_tex <- function(path, values) {
  lines <- c(
    "% Generated by manuscript/scripts/build-assets.R",
    unlist(lapply(names(values), function(name) {
      sprintf("\\newcommand{\\%s}{%s}", name, latex_escape(values[[name]]))
    }), use.names = FALSE)
  )

  writeLines(lines, con = path, useBytes = TRUE)
  invisible(path)
}

save_pdf_plot <- function(path, width, height, expr) {
  grDevices::pdf(path, width = width, height = height, useDingbats = FALSE)
  on.exit(grDevices::dev.off(), add = TRUE)

  force(expr)
  invisible(path)
}

set_method_colnames <- function(x) {
  colnames(x) <- c("Wilcoxon", "T-test", "LRT", "SPLRT")
  x
}
